### ISSUE TITLE
Linux support workaround 

### ISSUE THREAD

**Issue by kaldown** [stypr/clubhouse-py#3]
Since https://github.com/AgoraIO-Community/Agora-Python-SDK/issues/1 and **Agora** is a main dep.
Any plans to support **Linux** somehow ?

**Comment by stypr** [comment]
Thanks for adding an issue.

Agora's SDK provides Windows and OSX only. However, You can build up your own.

**Comment by kaldown** [comment]
But in order to do that, mac or win sdk should be downloaded.
Or this step can be skipped?

**Comment by stypr** [comment]
You need to build Agora's SDK in linux and use its so files to run in linux. 

you need to better check things out with Agora's src since you need to adjust drivers and settings that match your desktop environment in Linux. 

This question is something that is supposed to be asked in Agora's website, not here.
