### ISSUE TITLE
Signup error - Method "GET" not allowed

### ISSUE THREAD

**Issue by 0x366** [stypr/clubhouse-py#9]
python3 cli.py

1 )In docker with different version of python (3.6, 3.7, 3.8, 3.9). I don't understand why it's happening - because  it's `requests.post` request :

```
Please enter your phone number. (+818043217654) > +79099028132
{'detail': 'Method "GET" not allowed.'}
[-] Error occured during authentication. (None)
```

2) On OSX 11, using python3.9 I'm getting `HTTPSConnectionPool(host='www.clubhouseapi.com', port=443): Max retries exceeded with url: /api/start_phone_number_auth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))`

3) On OSX using app for requests, like - Insomnia - all working fine.

Anyone have thoughts why it may happen with python? I tried installing `requests[security]` - but it's didn't helped either

**Comment by stypr** [comment]
1. I guess you need to check your python in docker. Please test and give us some results before asking these kind of questions. Please manually test some codes and show us some detailed results. Are you attaching some proxy or something? Your question is too broad and even difficult to direct the issue. The code clearly sends POST data and you're asking here why GET is sent. Such situations are usually abnormal and it is likely to be caused by some Proxy or other factors..
(Ref. https://github.com/stypr/clubhouse-py/blob/v304/clubhouse.py#L98-L114 )

2. Read the error. Try to access https://www.clubhouseapi.com/ and see if the error still persists. It may be your system's issue, not mine.
